version: '3'

services:
  go-bot:
    build: .
    restart: always
    links:
      - db
    env_file:
      - .env
  import:
    build: .
    links:
      - db
    restart: "no"
    env_file:
      - .env
    entrypoint: ["./bot", "import_memes"]
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-pass}"
      POSTGRES_DB: "db"
    volumes:
      - ./postgres-data:/var/lib/postgresql
    ports:
      - "${POSTGRES_PORT:-5432}:5432"