version: '3'

services:
  go-bot:
    build: .
    restart: always
    env_file:
      - .env
  import:
    build: .
    restart: "no"
    env_file:
      - .env
    entrypoint: ["./bot", "import_memes"]
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD:-pass}"
      POSTGRES_DB: "db"
    ports:
      - "${POSTGRES_PORT}:5432"